version: "3.9"
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: desafio-imposto-app
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/imposto
      DB_USERNAME: postgres
      DB_PASSWORD: admin
    depends_on:
      - db

  db:
    image: postgres:13
    container_name: desafio-imposto-db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: imposto
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: